version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/target
    env_file:
      - ./backend/.env
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DEMO_BALLOT_IDS=102,103,104
    networks:
      - dev-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"  # Vite use 5173 port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    networks:
      - dev-network

  db:
    image: postgres:14
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - dev_db:/var/lib/postgresql/data
    networks:
      - dev-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  dev_db:
