FROM maven:3.9.4-eclipse-temurin-21

WORKDIR /app

# Copy pom.xml first for dependency caching
COPY pom.xml .

# Download dependencies
RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

VOLUME ["/app/target"]

CMD ["mvn", "spring-boot:run"]
